import { NavbarMain } from '@/components'
import '../../style/globals.css'
import { Inter } from 'next/font/google'
import PageWrapper from './pagewrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#f0f0f0] scrollbar-hide'>
      <PageWrapper>
        <div>
          <NavbarMain/>
          {children}
        </div>
      </PageWrapper>
      </body>
    </html>
  )
}
